"""Initial migration

Revision ID: 395da77ddc9a
Revises: 
Create Date: 2026-04-21 14:00:08.829462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395da77ddc9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('ncm', sa.String(), nullable=True),
    sa.Column('vol_mult', sa.Float(), nullable=True),
    sa.Column('predicted_values', sa.JSON(), nullable=True),
    sa.Column('input_seed_months', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_logs_id'), 'inference_logs', ['id'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncm', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('last_validation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_evaluations_id'), 'model_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_evaluations_id'), table_name='model_evaluations')
    op.drop_table('model_evaluations')
    op.drop_index(op.f('ix_inference_logs_id'), table_name='inference_logs')
    op.drop_table('inference_logs')
    # ### end Alembic commands ###
