"""Add API keys, report logs and indices

Revision ID: b8648b0f6fcb
Revises: 395da77ddc9a
Create Date: 2026-04-23 23:48:59.461595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8648b0f6fcb'
down_revision: Union[str, Sequence[str], None] = '395da77ddc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('report_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('ncm', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_logs_id'), 'report_logs', ['id'], unique=False)
    op.create_index(op.f('ix_report_logs_ncm'), 'report_logs', ['ncm'], unique=False)
    op.create_index(op.f('ix_report_logs_timestamp'), 'report_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_report_logs_uf'), 'report_logs', ['uf'], unique=False)
    op.create_index(op.f('ix_inference_logs_ncm'), 'inference_logs', ['ncm'], unique=False)
    op.create_index(op.f('ix_inference_logs_timestamp'), 'inference_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inference_logs_uf'), 'inference_logs', ['uf'], unique=False)
    op.create_index(op.f('ix_model_evaluations_ncm'), 'model_evaluations', ['ncm'], unique=False)
    op.create_index(op.f('ix_model_evaluations_uf'), 'model_evaluations', ['uf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_evaluations_uf'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_ncm'), table_name='model_evaluations')
    op.drop_index(op.f('ix_inference_logs_uf'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_timestamp'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_ncm'), table_name='inference_logs')
    op.drop_index(op.f('ix_report_logs_uf'), table_name='report_logs')
    op.drop_index(op.f('ix_report_logs_timestamp'), table_name='report_logs')
    op.drop_index(op.f('ix_report_logs_ncm'), table_name='report_logs')
    op.drop_index(op.f('ix_report_logs_id'), table_name='report_logs')
    op.drop_table('report_logs')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
